### ISSUE TITLE
how to start? 如何开始？

### ISSUE THREAD

**Issue by gatosdeolhosazuis** [shentar/jAlbum#11]
how do I run it locally?
如何在本地运行？

**Comment by u19900101** [comment]
> how do I run it locally?
> 如何在本地运行？

同问，大佬在本地调试好没有，求带

**Comment by shentar** [comment]
> > how do I run it locally?
> > 如何在本地运行？
> 
> 同问，大佬在本地调试好没有，求带

download代码，然后mvn install，能编译过的话，就到distrigute目录执行：
jalbum.sh start （linux os）
或者
start.bat （windows os）

剩下的是定制配置，需要仔细读一下配置文档呢。

**Comment by u19900101** [comment]
> > > how do I run it locally?
> > > 如何在本地运行？
> > 
> > 
> > 同问，大佬在本地调试好没有，求带
> 
> download代码，然后mvn install，能编译过的话，就到distribute目录执行：
> jalbum.sh start （linux os）
> 或者
> start.bat （windows os）
> 
> 剩下的是定制配置，需要仔细读一下配置文档呢。

拜读过主页的安装教程，但是没能编译成功，主页的Release包下载不了，应用示例的图片也404，还望大佬多多指点，或者您能发一个编译好的文件吗，感谢

**Comment by shentar** [comment]
@u19900101 
https://photo.codefine.site:12524/wp-content/uploads/2021/02/jAlbum_release_0.3.1.zip
你试下这个编译好的版本。

**Comment by u19900101** [comment]
收到，感谢大佬！


 
---原始邮件---
发件人: "Tong Yanqun"<notifications@github.com&gt;
发送时间: 2021年2月24日(星期三) 凌晨0:23
收件人: "shentar/jAlbum"<jAlbum@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"u19900101"<815000342@qq.com&gt;;
主题: Re: [shentar/jAlbum] how to start? 如何开始？ (#11)




 
@u19900101
 https://photo.codefine.site:12524/wp-content/uploads/2021/02/jAlbum_release_0.3.1.zip
 你试下这个编译好的版本。

**Comment by u19900101** [comment]
感谢大佬，我下载好之后，解压后运行start.bat，还是报错，求指点！！


这个是报错的日志，打扰了！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shentar/jAlbum"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月24日(星期三) 凌晨0:23
收件人:&nbsp;"shentar/jAlbum"<jAlbum@noreply.github.com&gt;;
抄送:&nbsp;"枫"<815000342@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [shentar/jAlbum] how to start? 如何开始？ (#11)





 
@u19900101
 https://photo.codefine.site:12524/wp-content/uploads/2021/02/jAlbum_release_0.3.1.zip
 你试下这个编译好的版本。

**Comment by u19900101** [comment]
> @u19900101
> https://photo.codefine.site:12524/wp-content/uploads/2021/02/jAlbum_release_0.3.1.zip
> 你试下这个编译好的版本。

已调通，谢谢！

**Comment by AlexandroGonSan** [comment]
Eu testarei depois. Muito obrigado!
